#!/bin/bash
# $Id: processpics,v 1.1 2021/03/01 15:31:08 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/processpics,v $
# $Revision: 1.1 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: processpics,v 1.1 2021/03/01 15:31:08 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.1 $ $Date: 2021/03/01 15:31:08 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

date=data
n=0
for ext in raw tif jpg ;do
	if [ -d $ext ]; then
		cd $ext
		n=`ls *.$ext|wc -l`
		read -p "$n images found in `pwd` ok? " ans
		[ $ans = "y" ] || echo "$cmd: images not found." >&2;exit
	fi
done
[ $n -lt 1 ] && echo "$cmd: no images found.">&2;exit
addcopright
cd ..
[ -r data ] || echo $cmd: $data not found." >&2;exit 
awk -F: <data '/^Roll/,/^Frames:/{print}/^A[A0]/{OFS=":";print($1,$2,$3)}'

